# cleaning Tuesday Dataset

## Importing libraries and Tuesday Data

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
tday=pd.read_csv("/content/drive/MyDrive/Depi Project/Data/TrafficLabelling/Tuesday-WorkingHours.pcap_ISCX.csv")

## Reading and undersatnding data

> head()

> info()

> shape

> describe()

> totalnull

> null percentage

> nunique()

In [ ]:
tday.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.3-192.168.10.5-88-49182-6,192.168.10.5,49182,192.168.10.3,88,6,4/7/2017 8:54,640,7,4,440,358.0,220,0,62.857143,107.349008,179,0,89.5,103.345698,1246875.000,17187.500000,64.000000,135.557286,445.0,1.0,640.0,106.666667,194.325157,497.0,1.0,538.0,179.333333,303.686242,530.0,4.0,0,0,0,0,164,104,10937.500000,6250.000000,0,220,66.500000,99.001837,9801.363636,0,0,0,1,0,0,0,0,0,72.545455,62.857143,89.5,164,0,0,0,0,0,0,7,440,4,358,8192,2053,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,192.168.10.3-192.168.10.5-88-49183-6,192.168.10.5,49183,192.168.10.3,88,6,4/7/2017 8:54,900,9,4,600,2944.0,300,0,66.666667,132.287566,1472,0,736.0,849.859596,3937777.778,14444.444440,75.000000,192.795228,684.0,1.0,900.0,112.500000,252.411229,734.0,1.0,766.0,255.333333,435.323252,758.0,3.0,0,0,0,0,204,104,10000.000000,4444.444444,0,1472,253.142857,527.434262,278186.901100,0,0,0,1,0,0,0,0,0,272.615385,66.666667,736.0,204,0,0,0,0,0,0,9,600,4,2944,8192,2053,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,192.168.10.3-192.168.10.5-88-49184-6,192.168.10.5,49184,192.168.10.3,88,6,4/7/2017 8:54,1205,7,4,2776,2830.0,1388,0,396.571429,677.274651,1415,0,707.5,816.950631,4652282.158,9128.630705,120.500000,236.433336,777.0,1.0,1205.0,200.833333,397.058392,1008.0,1.0,927.0,309.000000,491.647231,876.0,1.0,0,0,0,0,164,104,5809.128631,3319.502075,0,1415,467.166667,690.098917,476236.515200,0,0,0,1,0,0,0,0,0,509.636364,396.571429,707.5,164,0,0,0,0,0,0,7,2776,4,2830,8192,2053,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,192.168.10.3-192.168.10.5-88-49185-6,192.168.10.5,49185,192.168.10.3,88,6,4/7/2017 8:54,511,7,4,452,370.0,226,0,64.571429,110.276708,185,0,92.5,106.809800,1608610.568,21526.418790,51.100000,90.767652,299.0,1.0,511.0,85.166667,131.900594,349.0,1.0,462.0,154.000000,224.719826,412.0,1.0,0,0,0,0,164,104,13698.630140,7827.788650,0,226,68.500000,101.933579,10390.454550,0,0,0,1,0,0,0,0,0,74.727273,64.571429,92.5,164,0,0,0,0,0,0,7,452,4,370,8192,2053,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,192.168.10.3-192.168.10.5-88-49186-6,192.168.10.5,49186,192.168.10.3,88,6,4/7/2017 8:54,773,9,4,612,2944.0,306,0,68.000000,134.933317,1472,0,736.0,849.859596,4600258.732,16817.593790,64.416667,148.698266,531.0,1.0,773.0,96.625000,196.665733,580.0,1.0,675.0,225.000000,348.901132,627.0,1.0,0,0,0,0,204,104,11642.949550,5174.644243,0,1472,254.000000,527.520762,278278.153800,0,0,0,1,0,0,0,0,0,273.538461,68.000000,736.0,204,0,0,0,0,0,0,9,612,4,2944,8192,2053,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [ ]:
tday.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445909 entries, 0 to 445908
Data columns (total 85 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Flow ID                       445909 non-null  object
 1    Source IP                    445909 non-null  object
 2    Source Port                  445909 non-null  int64
 3    Destination IP               445909 non-null  object
 4    Destination Port             445909 non-null  int64
 5    Protocol                     445909 non-null  int64
 6    Timestamp                    445909 non-null  object
 7    Flow Duration                445909 non-null  int64
 8    Total Fwd Packets            445909 non-null  int64
 9    Total Backward Packets       445909 non-null  int64
 10  Total Length of Fwd Packets   445909 non-null  int64
 11   Total Length of Bwd Packets  445909 non-null  float64
 12   Fwd Packet Length Max        445909 non-null  int64
 13   Fwd Packet Length Min        445909 non-null  int64
 14   Fwd Packet Length Mean       445909 non-null  float64
 15   Fwd Packet Length Std        445909 non-null  float64
 16  Bwd Packet Length Max         445909 non-null  int64
 17   Bwd Packet Length Min        445909 non-null  int64
 18   Bwd Packet Length Mean       445909 non-null  float64
 19   Bwd Packet Length Std        445909 non-null  float64
 20  Flow Bytes/s                  445708 non-null  float64
 21   Flow Packets/s               445909 non-null  float64
 22   Flow IAT Mean                445909 non-null  float64
 23   Flow IAT Std                 445909 non-null  float64
 24   Flow IAT Max                 445909 non-null  float64
 25   Flow IAT Min                 445909 non-null  float64
 26  Fwd IAT Total                 445909 non-null  float64
 27   Fwd IAT Mean                 445909 non-null  float64
 28   Fwd IAT Std                  445909 non-null  float64
 29   Fwd IAT Max                  445909 non-null  float64
 30   Fwd IAT Min                  445909 non-null  float64
 31  Bwd IAT Total                 445909 non-null  float64
 32   Bwd IAT Mean                 445909 non-null  float64
 33   Bwd IAT Std                  445909 non-null  float64
 34   Bwd IAT Max                  445909 non-null  float64
 35   Bwd IAT Min                  445909 non-null  float64
 36  Fwd PSH Flags                 445909 non-null  int64
 37   Bwd PSH Flags                445909 non-null  int64
 38   Fwd URG Flags                445909 non-null  int64
 39   Bwd URG Flags                445909 non-null  int64
 40   Fwd Header Length            445909 non-null  int64
 41   Bwd Header Length            445909 non-null  int64
 42  Fwd Packets/s                 445909 non-null  float64
 43   Bwd Packets/s                445909 non-null  float64
 44   Min Packet Length            445909 non-null  int64
 45   Max Packet Length            445909 non-null  int64
 46   Packet Length Mean           445909 non-null  float64
 47   Packet Length Std            445909 non-null  float64
 48   Packet Length Variance       445909 non-null  float64
 49  FIN Flag Count                445909 non-null  int64
 50   SYN Flag Count               445909 non-null  int64
 51   RST Flag Count               445909 non-null  int64
 52   PSH Flag Count               445909 non-null  int64
 53   ACK Flag Count               445909 non-null  int64
 54   URG Flag Count               445909 non-null  int64
 55   CWE Flag Count               445909 non-null  int64
 56   ECE Flag Count               445909 non-null  int64
 57   Down/Up Ratio                445909 non-null  int64
 58   Average Packet Size          445909 non-null  float64
 59   Avg Fwd Segment Size         445909 non-null  float64
 60   Avg Bwd Segment Size         445909 non-null  float64
 61   Fwd Header Length.1          445909 non-null  int64
 62  Fwd Avg Bytes/Bulk            445909 non-null  int64
 63   Fwd Avg Packets/Bulk         445909 non-null  int64
 64   Fwd Avg Bulk Rate            445909 non-null  int64
 65   Bwd Avg Bytes/Bulk           445909 non-null  int64
 66   Bwd Avg Packets/Bulk         445909 non-null  int64
 67  Bwd Avg Bulk Rate             445909 non-null  int64
 68  Subflow Fwd Packets           445909 non-null  int64
 69   Subflow Fwd Bytes            445909 non-null  int64
 70   Subflow Bwd Packets          445909 non-null  int64
 71   Subflow Bwd Bytes            445909 non-null  int64
 72  Init_Win_bytes_forward        445909 non-null  int64
 73   Init_Win_bytes_backward      445909 non-null  int64
 74   act_data_pkt_fwd             445909 non-null  int64
 75   min_seg_size_forward         445909 non-null  int64
 76  Active Mean                   445909 non-null  float64
 77   Active Std                   445909 non-null  float64
 78   Active Max                   445909 non-null  float64
 79   Active Min                   445909 non-null  float64
 80  Idle Mean                     445909 non-null  float64
 81   Idle Std                     445909 non-null  float64
 82   Idle Max                     445909 non-null  float64
 83   Idle Min                     445909 non-null  float64
 84   Label                        445909 non-null  object
dtypes: float64(37), int64(43), object(5)
memory usage: 289.2+ MB

In [ ]:
tday.shape

(445909, 85)

In [ ]:
tday.isna().sum()

Flow ID                           0
 Source IP                        0
 Source Port                      0
 Destination IP                   0
 Destination Port                 0
 Protocol                         0
 Timestamp                        0
 Flow Duration                    0
 Total Fwd Packets                0
 Total Backward Packets           0
Total Length of Fwd Packets       0
 Total Length of Bwd Packets      0
 Fwd Packet Length Max            0
 Fwd Packet Length Min            0
 Fwd Packet Length Mean           0
 Fwd Packet Length Std            0
Bwd Packet Length Max             0
 Bwd Packet Length Min            0
 Bwd Packet Length Mean           0
 Bwd Packet Length Std            0
Flow Bytes/s                    201
 Flow Packets/s                   0
 Flow IAT Mean                    0
 Flow IAT Std                     0
 Flow IAT Max                     0
 Flow IAT Min                     0
Fwd IAT Total                     0
 Fwd IAT Mean                     0
 Fwd IAT Std                      0
 Fwd IAT Max                      0
 Fwd IAT Min                      0
Bwd IAT Total                     0
 Bwd IAT Mean                     0
 Bwd IAT Std                      0
 Bwd IAT Max                      0
 Bwd IAT Min                      0
Fwd PSH Flags                     0
 Bwd PSH Flags                    0
 Fwd URG Flags                    0
 Bwd URG Flags                    0
 Fwd Header Length                0
 Bwd Header Length                0
Fwd Packets/s                     0
 Bwd Packets/s                    0
 Min Packet Length                0
 Max Packet Length                0
 Packet Length Mean               0
 Packet Length Std                0
 Packet Length Variance           0
FIN Flag Count                    0
 SYN Flag Count                   0
 RST Flag Count                   0
 PSH Flag Count                   0
 ACK Flag Count                   0
 URG Flag Count                   0
 CWE Flag Count                   0
 ECE Flag Count                   0
 Down/Up Ratio                    0
 Average Packet Size              0
 Avg Fwd Segment Size             0
 Avg Bwd Segment Size             0
 Fwd Header Length.1              0
Fwd Avg Bytes/Bulk                0
 Fwd Avg Packets/Bulk             0
 Fwd Avg Bulk Rate                0
 Bwd Avg Bytes/Bulk               0
 Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                 0
Subflow Fwd Packets               0
 Subflow Fwd Bytes                0
 Subflow Bwd Packets              0
 Subflow Bwd Bytes                0
Init_Win_bytes_forward            0
 Init_Win_bytes_backward          0
 act_data_pkt_fwd                 0
 min_seg_size_forward             0
Active Mean                       0
 Active Std                       0
 Active Max                       0
 Active Min                       0
Idle Mean                         0
 Idle Std                         0
 Idle Max                         0
 Idle Min                         0
 Label                            0
dtype: int64

In [ ]:
tday.isna().sum()/len(tday)*100

Flow ID                         0.000000
 Source IP                      0.000000
 Source Port                    0.000000
 Destination IP                 0.000000
 Destination Port               0.000000
 Protocol                       0.000000
 Timestamp                      0.000000
 Flow Duration                  0.000000
 Total Fwd Packets              0.000000
 Total Backward Packets         0.000000
Total Length of Fwd Packets     0.000000
 Total Length of Bwd Packets    0.000000
 Fwd Packet Length Max          0.000000
 Fwd Packet Length Min          0.000000
 Fwd Packet Length Mean         0.000000
 Fwd Packet Length Std          0.000000
Bwd Packet Length Max           0.000000
 Bwd Packet Length Min          0.000000
 Bwd Packet Length Mean         0.000000
 Bwd Packet Length Std          0.000000
Flow Bytes/s                    0.045076
 Flow Packets/s                 0.000000
 Flow IAT Mean                  0.000000
 Flow IAT Std                   0.000000
 Flow IAT Max                   0.000000
 Flow IAT Min                   0.000000
Fwd IAT Total                   0.000000
 Fwd IAT Mean                   0.000000
 Fwd IAT Std                    0.000000
 Fwd IAT Max                    0.000000
 Fwd IAT Min                    0.000000
Bwd IAT Total                   0.000000
 Bwd IAT Mean                   0.000000
 Bwd IAT Std                    0.000000
 Bwd IAT Max                    0.000000
 Bwd IAT Min                    0.000000
Fwd PSH Flags                   0.000000
 Bwd PSH Flags                  0.000000
 Fwd URG Flags                  0.000000
 Bwd URG Flags                  0.000000
 Fwd Header Length              0.000000
 Bwd Header Length              0.000000
Fwd Packets/s                   0.000000
 Bwd Packets/s                  0.000000
 Min Packet Length              0.000000
 Max Packet Length              0.000000
 Packet Length Mean             0.000000
 Packet Length Std              0.000000
 Packet Length Variance         0.000000
FIN Flag Count                  0.000000
 SYN Flag Count                 0.000000
 RST Flag Count                 0.000000
 PSH Flag Count                 0.000000
 ACK Flag Count                 0.000000
 URG Flag Count                 0.000000
 CWE Flag Count                 0.000000
 ECE Flag Count                 0.000000
 Down/Up Ratio                  0.000000
 Average Packet Size            0.000000
 Avg Fwd Segment Size           0.000000
 Avg Bwd Segment Size           0.000000
 Fwd Header Length.1            0.000000
Fwd Avg Bytes/Bulk              0.000000
 Fwd Avg Packets/Bulk           0.000000
 Fwd Avg Bulk Rate              0.000000
 Bwd Avg Bytes/Bulk             0.000000
 Bwd Avg Packets/Bulk           0.000000
Bwd Avg Bulk Rate               0.000000
Subflow Fwd Packets             0.000000
 Subflow Fwd Bytes              0.000000
 Subflow Bwd Packets            0.000000
 Subflow Bwd Bytes              0.000000
Init_Win_bytes_forward          0.000000
 Init_Win_bytes_backward        0.000000
 act_data_pkt_fwd               0.000000
 min_seg_size_forward           0.000000
Active Mean                     0.000000
 Active Std                     0.000000
 Active Max                     0.000000
 Active Min                     0.000000
Idle Mean                       0.000000
 Idle Std                       0.000000
 Idle Max                       0.000000
 Idle Min                       0.000000
 Label                          0.000000
dtype: float64

In [ ]:
tday.describe()

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,445909.000000,445909.000000,445909.000000,4.459090e+05,445909.000000,445909.000000,4.459090e+05,4.459090e+05,445909.000000,445909.000000,445909.000000,445909.000000,445909.000000,445909.000000,445909.000000,445909.000000,4.457080e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,445909.000000,445909.0,445909.0,445909.0,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,445909.000000,445909.000000,445909.000000,445909.000000,4.459090e+05,445909.000000,445909.000000,445909.000000,445909.000000,445909.000000,445909.000000,445909.0,445909.000000,445909.00000,445909.000000,445909.000000,445909.000000,4.459090e+05,445909.0,445909.0,445909.0,445909.0,445909.0,445909.0,445909.000000,4.459090e+05,445909.000000,4.459090e+05,445909.000000,445909.000000,445909.000000,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05,4.459090e+05
mean,40434.596061,8878.375745,10.924852,1.077944e+07,11.800473,13.907212,5.302105e+02,2.186324e+04,173.346669,20.579979,48.528489,49.897094,426.185778,50.359952,170.371225,126.945652,inf,inf,8.969193e+05,1.457432e+06,3.983417e+06,1.617527e+05,1.049772e+07,1.894540e+06,1.038472e+06,3.880805e+06,1.218153e+06,9.818604e+06,1.792829e+06,8.081417e+05,3.348626e+06,1.202342e+06,0.060723,0.0,0.0,0.0,-1.502153e+05,-1.171400e+04,5.345103e+04,5.825596e+03,19.930762,465.214483,107.620046,135.258513,8.290961e+04,0.018380,0.060723,0.000336,0.242597,0.291687,0.115091,0.0,0.000339,0.68745,121.243156,48.528489,170.371225,-1.502153e+05,0.0,0.0,0.0,0.0,0.0,0.0,11.800473,5.302105e+02,13.907212,2.186163e+04,7408.452460,2792.060604,2.088341,-1.321786e+04,7.265964e+04,4.670517e+04,1.642092e+05,4.828426e+04,3.294459e+06,1.497105e+05,3.407025e+06,3.145407e+06
std,23963.014261,19522.889728,5.476455,2.955629e+07,867.072428,1172.161547,5.676904e+03,2.625768e+06,472.450792,38.938350,113.195021,146.736325,881.676023,73.694913,311.356700,284.234647,NaN,NaN,4.250992e+06,5.771200e+06,1.342159e+07,2.852817e+06,2.942314e+07,9.512342e+06,3.817298e+06,1.340005e+07,9.269572e+06,2.861556e+07,9.459806e+06,3.505231e+06,1.273227e+07,9.205516e+06,0.238822,0.0,0.0,0.0,5.289797e+07,3.595580e+06,2.240127e+05,3.544440e+04,26.280681,946.383526,190.497397,254.194714,2.594933e+05,0.134323,0.238822,0.018338,0.428654,0.454540,0.319132,0.0,0.018399,0.53444,196.527086,113.195021,311.356700,5.289797e+07,0.0,0.0,0.0,0.0,0.0,0.0,867.072428,5.676904e+03,1172.161547,2.625473e+06,15609.495614,9744.606181,6.325197,2.666478e+06,6.205625e+05,3.601504e+05,1.049887e+06,5.649489e+05,1.258776e+07,1.982346e+06,1.293249e+07,1.240892e+07
min,0.000000,0.000000,0.000000,-4.000000e+00,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,-2.000000e+06,-4.000000e+00,0.000000e+00,-4.000000e+00,-1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,-3.221223e+10,-1.073741e+09,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,-3.221223e+10,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000e+00,0.000000,0.000000e+00,-1.000000,-1.000000,0.000000,-5.368707e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,12592.000000,53.000000,6.000000,1.860000e+02,2.000000,1.000000,4.000000e+00,0.000000e+00,1.000000,0.000000,0.857143,0.000000,0.000000,0.000000,0.000000,0.000000,1.155286e+00,1.369028e+01,7.333333e+01,0.000000e+00,1.560000e+02,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,4.000000e+01,2.000000e+01,6.978197e+00,2.833362e-01,0.000000,14.000000,4.666667,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,5.750000,0.857143,0.000000,4.000000e+01,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,4.000000e+00,1.000000,0.000000e+00,-1.000000,-1.000000,0.000000,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,52102.000000,80.000000,6.000000,3.128800e+04,2.000000,2.000000,6.800000e+01,1.360000e+02,41.000000,0.000000,37.000000,0.000000,86.000000,0.000000,79.000000,0.000000,2.478017e+03,1.206163e+02,1.078433e+04,1.164231e+02,3.087600e+04,4.000000e+00,4.000000e+00,4.000000e+00,0.000000e+00,4.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,0.000000e+00,3.000000e+00,2.000000e+00,0.000000,0.0,0.0,0.0,6.400000e+01,4.000000e+01,6.311338e+01,2.810923e+01,0.000000,90.000000,58.600000,26.838405,7.203000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.00000,74.000000,37.000000,79.000000,6.400000e+01,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,6.800000e+01,2.000000,1.360000e+02,114.000000,-1.000000,1.000000,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,59298.000000,443.000000,17.000000,4.668200e+05,4.000000,2.000000,1.500000e+02,3.360000e+02,62.000000,41.000000,50.000000,21.920310,179.000000,96.000000,149.000000,0.000000,2.830738e+04,1.990050e+04,1.150287e+05,7.914402e+04,2.875780e+05,9.600000e+01,2.883820e+05,4.561979e+04,2.197122e+04,1.397250e+05,4.900000e+01,5.482400e+04,5.793000e+03,0.000000e+00,3.354900e+04,4.000000e+00,0.000000,0.0,0.0,0.0,1.040000e+02,8.000000e+01,1.030928e+04,5.813953e+03,41.000000,204.000000,91.400000,81.610661,6.660300e+03,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,1.00000,119.862069,50.000000,149.000000,1.040000e+02,0.0,0.0,0.0,0.0,0.0,0.0,4.000000,1.500000e+02,2.000000,3.360000e+02,8192.000000,247.000000,2.000000,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,65535.000000,65505.000000,17.000000,1.200000e+08,206446.000000,276072.000000,2.428415e+06,6.270000e+08,24820.000000,2065.000000,4672.000000,5398.072094,13140.000000,2896.000000,3735.736842,4113.240146,inf,inf,1.200000e+08,8.480000e+07,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08,8.440000e+07,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08,8.260000e+07,1.200000e+08,1.200000e+08,1.000000,0.0,0.0,0.0,4.225596e+06,5.521440e+06,3.000000e+06,2.000000e+06,1408.000000,24820.000000,3337.142857,3811.855065,1.450000e+07,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,35.00000,3893.333333,4672.000000,3735.736842,4.225596e+06,0.0,0.0,0.0,0.0,0.0,0.0,206446.000000,2.428415e+06,276072.000000,6.270390e+08,65535.000000,65535.000000,1846.000000,1.380000e+02,1.070000e+08,2.410000e+07,1.070000e+08,1.070000e+08,1.200000e+08,7.590000e+07,1.200000e+08,1.200000e+08

In [ ]:
for i in tday.columns:
    print(f"{i} : {tday[i].nunique()}")

Flow ID : 211628
 Source IP : 7192
 Source Port : 52554
 Destination IP : 8490
 Destination Port : 31858
 Protocol : 3
 Timestamp : 488
 Flow Duration : 195774
 Total Fwd Packets : 658
 Total Backward Packets : 828
Total Length of Fwd Packets : 8396
 Total Length of Bwd Packets : 23135
 Fwd Packet Length Max : 3441
 Fwd Packet Length Min : 187
 Fwd Packet Length Mean : 29206
 Fwd Packet Length Std : 52153
Bwd Packet Length Max : 3968
 Bwd Packet Length Min : 442
 Bwd Packet Length Mean : 39974
 Bwd Packet Length Std : 54599
Flow Bytes/s : 260375
 Flow Packets/s : 211867
 Flow IAT Mean : 206743
 Flow IAT Std : 189448
 Flow IAT Max : 135556
 Flow IAT Min : 45913
Fwd IAT Total : 94653
 Fwd IAT Mean : 143083
 Fwd IAT Std : 127890
 Fwd IAT Max : 94581
 Fwd IAT Min : 30883
Bwd IAT Total : 60416
 Bwd IAT Mean : 107830
 Bwd IAT Std : 100499
 Bwd IAT Max : 62937
 Bwd IAT Min : 14727
Fwd PSH Flags : 2
 Bwd PSH Flags : 1
 Fwd URG Flags : 1
 Bwd URG Flags : 1
 Fwd Header Length : 1776
 Bwd Header Length : 1892
Fwd Packets/s : 209853
 Bwd Packets/s : 196052
 Min Packet Length : 149
 Max Packet Length : 4443
 Packet Length Mean : 54597
 Packet Length Std : 77648
 Packet Length Variance : 77645
FIN Flag Count : 2
 SYN Flag Count : 2
 RST Flag Count : 2
 PSH Flag Count : 2
 ACK Flag Count : 2
 URG Flag Count : 2
 CWE Flag Count : 1
 ECE Flag Count : 2
 Down/Up Ratio : 16
 Average Packet Size : 53573
 Avg Fwd Segment Size : 29206
 Avg Bwd Segment Size : 39974
 Fwd Header Length.1 : 1776
Fwd Avg Bytes/Bulk : 1
 Fwd Avg Packets/Bulk : 1
 Fwd Avg Bulk Rate : 1
 Bwd Avg Bytes/Bulk : 1
 Bwd Avg Packets/Bulk : 1
Bwd Avg Bulk Rate : 1
Subflow Fwd Packets : 658
 Subflow Fwd Bytes : 8396
 Subflow Bwd Packets : 828
 Subflow Bwd Bytes : 23137
Init_Win_bytes_forward : 5670
 Init_Win_bytes_backward : 5718
 act_data_pkt_fwd : 189
 min_seg_size_forward : 17
Active Mean : 61215
 Active Std : 38808
 Active Max : 59456
 Active Min : 39811
Idle Mean : 30137
 Idle Std : 37827
 Idle Max : 15858
 Idle Min : 34560
 Label : 3

## Cleaning the tuesday's data

> removing the spaces in the columns name

> Dropping the null values as it is less than 0.045%

> removing duplicated values the null values

> removing useless coloumns

#### correcting column's name

In [ ]:
tday.columns=tday.columns.str.strip()
tday.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.3-192.168.10.5-88-49182-6,192.168.10.5,49182,192.168.10.3,88,6,4/7/2017 8:54,640,7,4,440,358.0,220,0,62.857143,107.349008,179,0,89.5,103.345698,1246875.000,17187.500000,64.000000,135.557286,445.0,1.0,640.0,106.666667,194.325157,497.0,1.0,538.0,179.333333,303.686242,530.0,4.0,0,0,0,0,164,104,10937.500000,6250.000000,0,220,66.500000,99.001837,9801.363636,0,0,0,1,0,0,0,0,0,72.545455,62.857143,89.5,164,0,0,0,0,0,0,7,440,4,358,8192,2053,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,192.168.10.3-192.168.10.5-88-49183-6,192.168.10.5,49183,192.168.10.3,88,6,4/7/2017 8:54,900,9,4,600,2944.0,300,0,66.666667,132.287566,1472,0,736.0,849.859596,3937777.778,14444.444440,75.000000,192.795228,684.0,1.0,900.0,112.500000,252.411229,734.0,1.0,766.0,255.333333,435.323252,758.0,3.0,0,0,0,0,204,104,10000.000000,4444.444444,0,1472,253.142857,527.434262,278186.901100,0,0,0,1,0,0,0,0,0,272.615385,66.666667,736.0,204,0,0,0,0,0,0,9,600,4,2944,8192,2053,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,192.168.10.3-192.168.10.5-88-49184-6,192.168.10.5,49184,192.168.10.3,88,6,4/7/2017 8:54,1205,7,4,2776,2830.0,1388,0,396.571429,677.274651,1415,0,707.5,816.950631,4652282.158,9128.630705,120.500000,236.433336,777.0,1.0,1205.0,200.833333,397.058392,1008.0,1.0,927.0,309.000000,491.647231,876.0,1.0,0,0,0,0,164,104,5809.128631,3319.502075,0,1415,467.166667,690.098917,476236.515200,0,0,0,1,0,0,0,0,0,509.636364,396.571429,707.5,164,0,0,0,0,0,0,7,2776,4,2830,8192,2053,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,192.168.10.3-192.168.10.5-88-49185-6,192.168.10.5,49185,192.168.10.3,88,6,4/7/2017 8:54,511,7,4,452,370.0,226,0,64.571429,110.276708,185,0,92.5,106.809800,1608610.568,21526.418790,51.100000,90.767652,299.0,1.0,511.0,85.166667,131.900594,349.0,1.0,462.0,154.000000,224.719826,412.0,1.0,0,0,0,0,164,104,13698.630140,7827.788650,0,226,68.500000,101.933579,10390.454550,0,0,0,1,0,0,0,0,0,74.727273,64.571429,92.5,164,0,0,0,0,0,0,7,452,4,370,8192,2053,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,192.168.10.3-192.168.10.5-88-49186-6,192.168.10.5,49186,192.168.10.3,88,6,4/7/2017 8:54,773,9,4,612,2944.0,306,0,68.000000,134.933317,1472,0,736.0,849.859596,4600258.732,16817.593790,64.416667,148.698266,531.0,1.0,773.0,96.625000,196.665733,580.0,1.0,675.0,225.000000,348.901132,627.0,1.0,0,0,0,0,204,104,11642.949550,5174.644243,0,1472,254.000000,527.520762,278278.153800,0,0,0,1,0,0,0,0,0,273.538461,68.000000,736.0,204,0,0,0,0,0,0,9,612,4,2944,8192,2053,2,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

#### drop nulls

In [ ]:
tday.dropna(inplace=True,axis=1)

In [ ]:
tday.isna().sum()

Flow ID                        0
Source IP                      0
Source Port                    0
Destination IP                 0
Destination Port               0
Protocol                       0
Timestamp                      0
Flow Duration                  0
Total Fwd Packets              0
Total Backward Packets         0
Total Length of Fwd Packets    0
Total Length of Bwd Packets    0
Fwd Packet Length Max          0
Fwd Packet Length Min          0
Fwd Packet Length Mean         0
Fwd Packet Length Std          0
Bwd Packet Length Max          0
Bwd Packet Length Min          0
Bwd Packet Length Mean         0
Bwd Packet Length Std          0
Flow Packets/s                 0
Flow IAT Mean                  0
Flow IAT Std                   0
Flow IAT Max                   0
Flow IAT Min                   0
Fwd IAT Total                  0
Fwd IAT Mean                   0
Fwd IAT Std                    0
Fwd IAT Max                    0
Fwd IAT Min                    0
Bwd IAT Total                  0
Bwd IAT Mean                   0
Bwd IAT Std                    0
Bwd IAT Max                    0
Bwd IAT Min                    0
Fwd PSH Flags                  0
Bwd PSH Flags                  0
Fwd URG Flags                  0
Bwd URG Flags                  0
Fwd Header Length              0
Bwd Header Length              0
Fwd Packets/s                  0
Bwd Packets/s                  0
Min Packet Length              0
Max Packet Length              0
Packet Length Mean             0
Packet Length Std              0
Packet Length Variance         0
FIN Flag Count                 0
SYN Flag Count                 0
RST Flag Count                 0
PSH Flag Count                 0
ACK Flag Count                 0
URG Flag Count                 0
CWE Flag Count                 0
ECE Flag Count                 0
Down/Up Ratio                  0
Average Packet Size            0
Avg Fwd Segment Size           0
Avg Bwd Segment Size           0
Fwd Header Length.1            0
Fwd Avg Bytes/Bulk             0
Fwd Avg Packets/Bulk           0
Fwd Avg Bulk Rate              0
Bwd Avg Bytes/Bulk             0
Bwd Avg Packets/Bulk           0
Bwd Avg Bulk Rate              0
Subflow Fwd Packets            0
Subflow Fwd Bytes              0
Subflow Bwd Packets            0
Subflow Bwd Bytes              0
Init_Win_bytes_forward         0
Init_Win_bytes_backward        0
act_data_pkt_fwd               0
min_seg_size_forward           0
Active Mean                    0
Active Std                     0
Active Max                     0
Active Min                     0
Idle Mean                      0
Idle Std                       0
Idle Max                       0
Idle Min                       0
Label                          0
dtype: int64

#### remove duplicated

In [ ]:
tday.duplicated().sum()

np.int64(4)

In [ ]:
tday.drop_duplicates(inplace=True)
tday.duplicated().sum()

np.int64(0)

In [ ]:
tday.to_csv('/content/drive/MyDrive/Depi Project/Cleaned Data/Cleaned_Tuesday.csv', index=False)