# Wednesday Datase

## Importing libraries and Wednesday Data

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
wday=pd.read_csv("/content/drive/MyDrive/Depi Project/Data/TrafficLabelling/Wednesday-workingHours.pcap_ISCX.csv")

## Reading and undersatnding data

> head()

> info()

> shape

> describe()

> totalnull

> null percentage

> nunique()

In [ ]:
wday.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.14-209.48.71.168-49459-80-6,192.168.10.14,49459,209.48.71.168,80,6,5/7/2017 8:42,38308,1,1,6,6.0,6,6,6.000000,0.000000,6,6,6.000000,0.000000,3.132505e+02,52.208416,38308.000000,0.000000,38308.0,38308.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0,0,0,0,20,20,26.104208,26.104208,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,1,0,0,1,9.000000,6.000000,6.000000,20,0,0,0,0,0,0,1,6,1,6,255,946,0,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,192.168.10.3-192.168.10.17-389-49453-6,192.168.10.17,49453,192.168.10.3,389,6,5/7/2017 8:42,479,11,5,172,326.0,79,0,15.636364,31.449238,163,0,65.200000,89.278777,1.039666e+06,33402.922760,31.933333,25.510409,73.0,0.0,479.0,47.900000,38.942836,109.0,1.0,401.0,100.250000,101.736178,237.0,3.0,0,0,0,0,368,176,22964.509390,10438.413360,0,163,29.294118,56.529599,3195.595588,0,0,0,1,0,0,0,0,0,31.125000,15.636364,65.200000,368,0,0,0,0,0,0,11,172,5,326,29200,260,4,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,192.168.10.3-192.168.10.17-88-46124-6,192.168.10.17,46124,192.168.10.3,88,6,5/7/2017 8:42,1095,10,6,3150,3150.0,1575,0,315.000000,632.561635,1575,0,525.000000,813.326503,5.753425e+06,14611.872150,73.000000,204.960972,810.0,1.0,1095.0,121.666667,298.746130,915.0,1.0,995.0,199.000000,345.535092,810.0,3.0,0,0,0,0,336,208,9132.420091,5479.452055,0,1575,370.588235,671.751541,451250.132400,0,0,0,1,0,0,0,0,0,393.750000,315.000000,525.000000,336,0,0,0,0,0,0,10,3150,6,3150,29200,2081,3,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,192.168.10.3-192.168.10.17-389-49454-6,192.168.10.17,49454,192.168.10.3,389,6,5/7/2017 8:42,15206,17,12,3452,6660.0,1313,0,203.058823,425.778474,3069,0,555.000000,977.480342,6.650007e+05,1907.141918,543.071429,2519.931377,13391.0,0.0,15206.0,950.375000,3322.417812,13391.0,2.0,15112.0,1373.818182,4176.449588,13961.0,3.0,0,0,0,0,560,388,1117.979745,789.162173,0,3069,337.066667,704.654082,496537.374700,0,0,0,1,0,0,0,0,0,348.689655,203.058823,555.000000,560,0,0,0,0,0,0,17,3452,12,6660,29200,0,10,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,192.168.10.3-192.168.10.17-88-46126-6,192.168.10.17,46126,192.168.10.3,88,6,5/7/2017 8:42,1092,9,6,3150,3152.0,1575,0,350.000000,694.509719,1576,0,525.333333,813.842901,5.771062e+06,13736.263740,78.000000,207.000929,794.0,1.0,1092.0,136.500000,313.850738,910.0,1.0,1015.0,203.000000,333.240154,794.0,3.0,0,0,0,0,304,208,8241.758242,5494.505495,0,1576,393.875000,704.585067,496440.116700,0,0,0,1,0,0,0,0,0,420.133333,350.000000,525.333333,304,0,0,0,0,0,0,9,3150,6,3152,29200,2081,2,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

In [ ]:
wday.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692703 entries, 0 to 692702
Data columns (total 85 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Flow ID                       692703 non-null  object
 1    Source IP                    692703 non-null  object
 2    Source Port                  692703 non-null  int64
 3    Destination IP               692703 non-null  object
 4    Destination Port             692703 non-null  int64
 5    Protocol                     692703 non-null  int64
 6    Timestamp                    692703 non-null  object
 7    Flow Duration                692703 non-null  int64
 8    Total Fwd Packets            692703 non-null  int64
 9    Total Backward Packets       692703 non-null  int64
 10  Total Length of Fwd Packets   692703 non-null  int64
 11   Total Length of Bwd Packets  692703 non-null  float64
 12   Fwd Packet Length Max        692703 non-null  int64
 13   Fwd Packet Length Min        692703 non-null  int64
 14   Fwd Packet Length Mean       692703 non-null  float64
 15   Fwd Packet Length Std        692703 non-null  float64
 16  Bwd Packet Length Max         692703 non-null  int64
 17   Bwd Packet Length Min        692703 non-null  int64
 18   Bwd Packet Length Mean       692703 non-null  float64
 19   Bwd Packet Length Std        692703 non-null  float64
 20  Flow Bytes/s                  691695 non-null  float64
 21   Flow Packets/s               692703 non-null  float64
 22   Flow IAT Mean                692703 non-null  float64
 23   Flow IAT Std                 692703 non-null  float64
 24   Flow IAT Max                 692703 non-null  float64
 25   Flow IAT Min                 692703 non-null  float64
 26  Fwd IAT Total                 692703 non-null  float64
 27   Fwd IAT Mean                 692703 non-null  float64
 28   Fwd IAT Std                  692703 non-null  float64
 29   Fwd IAT Max                  692703 non-null  float64
 30   Fwd IAT Min                  692703 non-null  float64
 31  Bwd IAT Total                 692703 non-null  float64
 32   Bwd IAT Mean                 692703 non-null  float64
 33   Bwd IAT Std                  692703 non-null  float64
 34   Bwd IAT Max                  692703 non-null  float64
 35   Bwd IAT Min                  692703 non-null  float64
 36  Fwd PSH Flags                 692703 non-null  int64
 37   Bwd PSH Flags                692703 non-null  int64
 38   Fwd URG Flags                692703 non-null  int64
 39   Bwd URG Flags                692703 non-null  int64
 40   Fwd Header Length            692703 non-null  int64
 41   Bwd Header Length            692703 non-null  int64
 42  Fwd Packets/s                 692703 non-null  float64
 43   Bwd Packets/s                692703 non-null  float64
 44   Min Packet Length            692703 non-null  int64
 45   Max Packet Length            692703 non-null  int64
 46   Packet Length Mean           692703 non-null  float64
 47   Packet Length Std            692703 non-null  float64
 48   Packet Length Variance       692703 non-null  float64
 49  FIN Flag Count                692703 non-null  int64
 50   SYN Flag Count               692703 non-null  int64
 51   RST Flag Count               692703 non-null  int64
 52   PSH Flag Count               692703 non-null  int64
 53   ACK Flag Count               692703 non-null  int64
 54   URG Flag Count               692703 non-null  int64
 55   CWE Flag Count               692703 non-null  int64
 56   ECE Flag Count               692703 non-null  int64
 57   Down/Up Ratio                692703 non-null  int64
 58   Average Packet Size          692703 non-null  float64
 59   Avg Fwd Segment Size         692703 non-null  float64
 60   Avg Bwd Segment Size         692703 non-null  float64
 61   Fwd Header Length.1          692703 non-null  int64
 62  Fwd Avg Bytes/Bulk            692703 non-null  int64
 63   Fwd Avg Packets/Bulk         692703 non-null  int64
 64   Fwd Avg Bulk Rate            692703 non-null  int64
 65   Bwd Avg Bytes/Bulk           692703 non-null  int64
 66   Bwd Avg Packets/Bulk         692703 non-null  int64
 67  Bwd Avg Bulk Rate             692703 non-null  int64
 68  Subflow Fwd Packets           692703 non-null  int64
 69   Subflow Fwd Bytes            692703 non-null  int64
 70   Subflow Bwd Packets          692703 non-null  int64
 71   Subflow Bwd Bytes            692703 non-null  int64
 72  Init_Win_bytes_forward        692703 non-null  int64
 73   Init_Win_bytes_backward      692703 non-null  int64
 74   act_data_pkt_fwd             692703 non-null  int64
 75   min_seg_size_forward         692703 non-null  int64
 76  Active Mean                   692703 non-null  float64
 77   Active Std                   692703 non-null  float64
 78   Active Max                   692703 non-null  float64
 79   Active Min                   692703 non-null  float64
 80  Idle Mean                     692703 non-null  float64
 81   Idle Std                     692703 non-null  float64
 82   Idle Max                     692703 non-null  float64
 83   Idle Min                     692703 non-null  float64
 84   Label                        692703 non-null  object
dtypes: float64(37), int64(43), object(5)
memory usage: 449.2+ MB

In [ ]:
wday.shape

(692703, 85)

In [ ]:
wday.describe()

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,692703.000000,692703.000000,692703.000000,6.927030e+05,692703.000000,692703.000000,6.927030e+05,6.927030e+05,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,6.916950e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,692703.000000,692703.0,692703.0,692703.0,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,692703.000000,692703.000000,692703.000000,692703.000000,6.927030e+05,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,692703.0,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,6.927030e+05,692703.0,692703.0,692703.0,692703.0,692703.0,692703.0,692703.000000,6.927030e+05,692703.000000,6.927030e+05,692703.000000,692703.000000,692703.000000,692703.000000,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05
mean,42583.995907,5686.869462,9.219523,2.800168e+07,9.556261,10.214079,5.550930e+02,1.699644e+04,233.593936,15.022183,60.555440,82.895863,1661.546313,33.832924,551.940841,658.636320,inf,inf,2.502809e+06,6.844318e+06,2.289307e+07,2.224592e+05,2.774476e+07,5.069287e+06,9.016685e+06,2.279837e+07,1.030778e+06,1.386407e+07,2.647068e+06,3.522882e+06,9.305284e+06,9.268549e+05,0.042201,0.0,0.0,0.0,2.420580e+02,2.492460e+02,9.545305e+04,4.052544e+03,13.723771,1725.129073,278.246605,523.265612,8.876018e+05,0.097301,0.042201,0.000338,0.193693,0.418049,0.066372,0.0,0.000339,0.556957,305.664882,60.555440,551.940841,2.420580e+02,0.0,0.0,0.0,0.0,0.0,0.0,9.556261,5.550930e+02,10.214079,1.699489e+04,5299.671256,1476.643078,6.121279,26.761141,9.224478e+04,4.760852e+04,1.627363e+05,6.315186e+04,2.211122e+07,4.743744e+05,2.252174e+07,2.173373e+07
std,19535.697710,15727.423560,5.009796,4.276680e+07,747.197814,984.204633,6.163663e+03,2.241175e+06,603.751856,51.068835,157.643794,226.126084,2613.924428,64.586498,797.449564,1098.043102,NaN,NaN,5.595945e+06,1.175401e+07,3.839395e+07,3.673248e+06,4.277094e+07,1.103613e+07,1.600574e+07,3.843629e+07,8.866760e+06,3.335293e+07,9.593760e+06,1.073828e+07,2.616633e+07,8.107914e+06,0.201048,0.0,0.0,0.0,1.564277e+04,1.968957e+04,3.198607e+05,3.091927e+04,27.521716,2634.372188,369.130494,783.442461,1.748895e+06,0.296368,0.201048,0.018376,0.395192,0.493239,0.248931,0.0,0.018416,0.570734,398.045939,157.643794,797.449564,1.564277e+04,0.0,0.0,0.0,0.0,0.0,0.0,747.197814,6.163663e+03,984.204633,2.240953e+06,11869.737394,7315.272621,715.155068,6.322368,7.007049e+05,4.742081e+05,1.094616e+06,6.051023e+05,3.812415e+07,4.488512e+06,3.848292e+07,3.807725e+07
min,0.000000,0.000000,0.000000,-1.000000e+00,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.200000e+07,-2.000000e+06,-1.000000e+00,0.000000e+00,-1.000000e+00,-1.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-8.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,-1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,-1.100000e+01,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000e+00,0.000000,0.000000e+00,-1.000000,-1.000000,0.000000,-1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,36235.000000,53.000000,6.000000,2.010000e+02,2.000000,1.000000,1.200000e+01,0.000000e+00,6.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.028251e+02,2.857569e-01,7.900000e+01,0.000000e+00,1.730000e+02,1.000000e+00,3.000000e+00,3.000000e+00,0.000000e+00,3.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,4.000000e+01,2.000000e+01,1.492719e-01,5.941689e-02,0.000000,6.000000,6.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,9.000000,6.000000,0.000000,4.000000e+01,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,1.200000e+01,1.000000,0.000000e+00,-1.000000,-1.000000,0.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,49822.000000,80.000000,6.000000,6.143700e+04,2.000000,2.000000,8.200000e+01,1.880000e+02,46.000000,0.000000,41.000000,0.000000,113.000000,0.000000,102.000000,0.000000,5.190026e+02,6.338341e+01,2.509567e+04,1.509993e+04,5.451000e+04,3.000000e+00,1.002000e+03,9.670000e+02,0.000000e+00,9.960000e+02,3.000000e+00,4.000000e+00,4.000000e+00,0.000000e+00,4.000000e+00,3.000000e+00,0.000000,0.0,0.0,0.0,6.400000e+01,6.400000e+01,3.172891e+01,3.602232e-01,0.000000,123.000000,70.454545,43.323259,1.876905e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,91.000000,41.000000,102.000000,6.400000e+01,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,8.200000e+01,2.000000,1.880000e+02,251.000000,0.000000,1.000000,32.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,56892.000000,443.000000,17.000000,8.302437e+07,7.000000,6.000000,3.650000e+02,1.159500e+04,341.000000,32.000000,56.666667,128.916917,2896.000000,58.000000,917.600000,927.603358,1.890071e+04,1.834862e+04,3.706981e+06,4.973849e+06,2.500000e+07,4.900000e+01,8.290000e+07,6.997846e+06,5.009074e+06,2.370000e+07,4.900000e+01,1.575400e+05,3.609575e+04,5.970159e+04,1.382425e+05,4.800000e+01,0.000000,0.0,0.0,0.0,2.000000e+02,2.000000e+02,9.708738e+03,6.104633e+01,32.000000,3072.000000,663.833333,984.512580,9.692650e+05,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,1.000000,696.065619,56.666667,917.600000,2.000000e+02,0.0,0.0,0.0,0.0,0.0,0.0,7.000000,3.650000e+02,6.000000,1.159500e+04,485.500000,235.000000,2.000000,32.000000,9.910000e+02,0.000000e+00,9.910000e+02,9.880000e+02,1.590000e+07,0.000000e+00,1.650000e+07,1.000000e+07
max,65535.000000,65487.000000,17.000000,1.200000e+08,203943.000000,272353.000000,1.224076e+06,6.270000e+08,24820.000000,2065.000000,4640.757576,6429.190773,19530.000000,1983.000000,4370.686524,6715.738331,inf,inf,1.200000e+08,8.480000e+07,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08,8.370000e+07,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08,8.290000e+07,1.200000e+08,1.200000e+08,1.000000,0.0,0.0,0.0,4.290372e+06,5.447060e+06,3.000000e+06,2.000000e+06,1448.000000,24820.000000,2279.754386,4364.022571,1.900000e+07,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,43.000000,2612.000000,4640.757576,4370.686524,4.290372e+06,0.0,0.0,0.0,0.0,0.0,0.0,203943.000000,1.224076e+06,272353.000000,6.270464e+08,65535.000000,65535.000000,197124.000000,60.000000,1.000000e+08,7.420000e+07,1.050000e+08,1.000000e+08,1.200000e+08,7.690000e+07,1.200000e+08,1.200000e+08

In [ ]:
wday.isna().sum()

Flow ID                            0
 Source IP                         0
 Source Port                       0
 Destination IP                    0
 Destination Port                  0
 Protocol                          0
 Timestamp                         0
 Flow Duration                     0
 Total Fwd Packets                 0
 Total Backward Packets            0
Total Length of Fwd Packets        0
 Total Length of Bwd Packets       0
 Fwd Packet Length Max             0
 Fwd Packet Length Min             0
 Fwd Packet Length Mean            0
 Fwd Packet Length Std             0
Bwd Packet Length Max              0
 Bwd Packet Length Min             0
 Bwd Packet Length Mean            0
 Bwd Packet Length Std             0
Flow Bytes/s                    1008
 Flow Packets/s                    0
 Flow IAT Mean                     0
 Flow IAT Std                      0
 Flow IAT Max                      0
 Flow IAT Min                      0
Fwd IAT Total                      0
 Fwd IAT Mean                      0
 Fwd IAT Std                       0
 Fwd IAT Max                       0
 Fwd IAT Min                       0
Bwd IAT Total                      0
 Bwd IAT Mean                      0
 Bwd IAT Std                       0
 Bwd IAT Max                       0
 Bwd IAT Min                       0
Fwd PSH Flags                      0
 Bwd PSH Flags                     0
 Fwd URG Flags                     0
 Bwd URG Flags                     0
 Fwd Header Length                 0
 Bwd Header Length                 0
Fwd Packets/s                      0
 Bwd Packets/s                     0
 Min Packet Length                 0
 Max Packet Length                 0
 Packet Length Mean                0
 Packet Length Std                 0
 Packet Length Variance            0
FIN Flag Count                     0
 SYN Flag Count                    0
 RST Flag Count                    0
 PSH Flag Count                    0
 ACK Flag Count                    0
 URG Flag Count                    0
 CWE Flag Count                    0
 ECE Flag Count                    0
 Down/Up Ratio                     0
 Average Packet Size               0
 Avg Fwd Segment Size              0
 Avg Bwd Segment Size              0
 Fwd Header Length.1               0
Fwd Avg Bytes/Bulk                 0
 Fwd Avg Packets/Bulk              0
 Fwd Avg Bulk Rate                 0
 Bwd Avg Bytes/Bulk                0
 Bwd Avg Packets/Bulk              0
Bwd Avg Bulk Rate                  0
Subflow Fwd Packets                0
 Subflow Fwd Bytes                 0
 Subflow Bwd Packets               0
 Subflow Bwd Bytes                 0
Init_Win_bytes_forward             0
 Init_Win_bytes_backward           0
 act_data_pkt_fwd                  0
 min_seg_size_forward              0
Active Mean                        0
 Active Std                        0
 Active Max                        0
 Active Min                        0
Idle Mean                          0
 Idle Std                          0
 Idle Max                          0
 Idle Min                          0
 Label                             0
dtype: int64

In [ ]:
wday.isna().sum()/len(wday)*100

Flow ID                         0.000000
 Source IP                      0.000000
 Source Port                    0.000000
 Destination IP                 0.000000
 Destination Port               0.000000
 Protocol                       0.000000
 Timestamp                      0.000000
 Flow Duration                  0.000000
 Total Fwd Packets              0.000000
 Total Backward Packets         0.000000
Total Length of Fwd Packets     0.000000
 Total Length of Bwd Packets    0.000000
 Fwd Packet Length Max          0.000000
 Fwd Packet Length Min          0.000000
 Fwd Packet Length Mean         0.000000
 Fwd Packet Length Std          0.000000
Bwd Packet Length Max           0.000000
 Bwd Packet Length Min          0.000000
 Bwd Packet Length Mean         0.000000
 Bwd Packet Length Std          0.000000
Flow Bytes/s                    0.145517
 Flow Packets/s                 0.000000
 Flow IAT Mean                  0.000000
 Flow IAT Std                   0.000000
 Flow IAT Max                   0.000000
 Flow IAT Min                   0.000000
Fwd IAT Total                   0.000000
 Fwd IAT Mean                   0.000000
 Fwd IAT Std                    0.000000
 Fwd IAT Max                    0.000000
 Fwd IAT Min                    0.000000
Bwd IAT Total                   0.000000
 Bwd IAT Mean                   0.000000
 Bwd IAT Std                    0.000000
 Bwd IAT Max                    0.000000
 Bwd IAT Min                    0.000000
Fwd PSH Flags                   0.000000
 Bwd PSH Flags                  0.000000
 Fwd URG Flags                  0.000000
 Bwd URG Flags                  0.000000
 Fwd Header Length              0.000000
 Bwd Header Length              0.000000
Fwd Packets/s                   0.000000
 Bwd Packets/s                  0.000000
 Min Packet Length              0.000000
 Max Packet Length              0.000000
 Packet Length Mean             0.000000
 Packet Length Std              0.000000
 Packet Length Variance         0.000000
FIN Flag Count                  0.000000
 SYN Flag Count                 0.000000
 RST Flag Count                 0.000000
 PSH Flag Count                 0.000000
 ACK Flag Count                 0.000000
 URG Flag Count                 0.000000
 CWE Flag Count                 0.000000
 ECE Flag Count                 0.000000
 Down/Up Ratio                  0.000000
 Average Packet Size            0.000000
 Avg Fwd Segment Size           0.000000
 Avg Bwd Segment Size           0.000000
 Fwd Header Length.1            0.000000
Fwd Avg Bytes/Bulk              0.000000
 Fwd Avg Packets/Bulk           0.000000
 Fwd Avg Bulk Rate              0.000000
 Bwd Avg Bytes/Bulk             0.000000
 Bwd Avg Packets/Bulk           0.000000
Bwd Avg Bulk Rate               0.000000
Subflow Fwd Packets             0.000000
 Subflow Fwd Bytes              0.000000
 Subflow Bwd Packets            0.000000
 Subflow Bwd Bytes              0.000000
Init_Win_bytes_forward          0.000000
 Init_Win_bytes_backward        0.000000
 act_data_pkt_fwd               0.000000
 min_seg_size_forward           0.000000
Active Mean                     0.000000
 Active Std                     0.000000
 Active Max                     0.000000
 Active Min                     0.000000
Idle Mean                       0.000000
 Idle Std                       0.000000
 Idle Max                       0.000000
 Idle Min                       0.000000
 Label                          0.000000
dtype: float64

In [ ]:
for i in wday.columns:
    print(f"{i} : {wday[i].nunique()}")

Flow ID : 226768
 Source IP : 7689
 Source Port : 54556
 Destination IP : 9012
 Destination Port : 30094
 Protocol : 3
 Timestamp : 509
 Flow Duration : 363185
 Total Fwd Packets : 685
 Total Backward Packets : 859
Total Length of Fwd Packets : 9380
 Total Length of Bwd Packets : 23483
 Fwd Packet Length Max : 3728
 Fwd Packet Length Min : 220
 Fwd Packet Length Mean : 31471
 Fwd Packet Length Std : 63498
Bwd Packet Length Max : 3836
 Bwd Packet Length Min : 429
 Bwd Packet Length Mean : 41095
 Bwd Packet Length Std : 55643
Flow Bytes/s : 450841
 Flow Packets/s : 387031
 Flow IAT Mean : 370810
 Flow IAT Std : 222370
 Flow IAT Max : 148528
 Flow IAT Min : 47743
Fwd IAT Total : 100832
 Fwd IAT Mean : 162817
 Fwd IAT Std : 142925
 Fwd IAT Max : 98682
 Fwd IAT Min : 37400
Bwd IAT Total : 111743
 Bwd IAT Mean : 181207
 Bwd IAT Std : 211343
 Bwd IAT Max : 105600
 Bwd IAT Min : 18812
Fwd PSH Flags : 2
 Bwd PSH Flags : 1
 Fwd URG Flags : 1
 Bwd URG Flags : 1
 Fwd Header Length : 1746
 Bwd Header Length : 1910
Fwd Packets/s : 382443
 Bwd Packets/s : 358777
 Min Packet Length : 166
 Max Packet Length : 4469
 Packet Length Mean : 61803
 Packet Length Std : 135696
 Packet Length Variance : 133816
FIN Flag Count : 2
 SYN Flag Count : 2
 RST Flag Count : 2
 PSH Flag Count : 2
 ACK Flag Count : 2
 URG Flag Count : 2
 CWE Flag Count : 1
 ECE Flag Count : 2
 Down/Up Ratio : 17
 Average Packet Size : 60919
 Avg Fwd Segment Size : 31471
 Avg Bwd Segment Size : 41095
 Fwd Header Length.1 : 1746
Fwd Avg Bytes/Bulk : 1
 Fwd Avg Packets/Bulk : 1
 Fwd Avg Bulk Rate : 1
 Bwd Avg Bytes/Bulk : 1
 Bwd Avg Packets/Bulk : 1
Bwd Avg Bulk Rate : 1
Subflow Fwd Packets : 685
 Subflow Fwd Bytes : 9380
 Subflow Bwd Packets : 859
 Subflow Bwd Bytes : 23486
Init_Win_bytes_forward : 5698
 Init_Win_bytes_backward : 6049
 act_data_pkt_fwd : 564
 min_seg_size_forward : 13
Active Mean : 78864
 Active Std : 44220
 Active Max : 76777
 Active Min : 53325
Idle Mean : 37601
 Idle Std : 41528
 Idle Max : 21986
 Idle Min : 43869
 Label : 6

## Cleaning the Wednesday's data

> removing the spaces in the columns name

> Dropping the null values as it is less than 0.045%

> removing duplicated values the null values

> removing useless coloumns

#### correcting column's name

In [ ]:
wday.columns=wday.columns.str.strip()
wday.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.14-209.48.71.168-49459-80-6,192.168.10.14,49459,209.48.71.168,80,6,5/7/2017 8:42,38308,1,1,6,6.0,6,6,6.000000,0.000000,6,6,6.000000,0.000000,3.132505e+02,52.208416,38308.000000,0.000000,38308.0,38308.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0,0,0,0,20,20,26.104208,26.104208,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,1,0,0,1,9.000000,6.000000,6.000000,20,0,0,0,0,0,0,1,6,1,6,255,946,0,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,192.168.10.3-192.168.10.17-389-49453-6,192.168.10.17,49453,192.168.10.3,389,6,5/7/2017 8:42,479,11,5,172,326.0,79,0,15.636364,31.449238,163,0,65.200000,89.278777,1.039666e+06,33402.922760,31.933333,25.510409,73.0,0.0,479.0,47.900000,38.942836,109.0,1.0,401.0,100.250000,101.736178,237.0,3.0,0,0,0,0,368,176,22964.509390,10438.413360,0,163,29.294118,56.529599,3195.595588,0,0,0,1,0,0,0,0,0,31.125000,15.636364,65.200000,368,0,0,0,0,0,0,11,172,5,326,29200,260,4,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,192.168.10.3-192.168.10.17-88-46124-6,192.168.10.17,46124,192.168.10.3,88,6,5/7/2017 8:42,1095,10,6,3150,3150.0,1575,0,315.000000,632.561635,1575,0,525.000000,813.326503,5.753425e+06,14611.872150,73.000000,204.960972,810.0,1.0,1095.0,121.666667,298.746130,915.0,1.0,995.0,199.000000,345.535092,810.0,3.0,0,0,0,0,336,208,9132.420091,5479.452055,0,1575,370.588235,671.751541,451250.132400,0,0,0,1,0,0,0,0,0,393.750000,315.000000,525.000000,336,0,0,0,0,0,0,10,3150,6,3150,29200,2081,3,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,192.168.10.3-192.168.10.17-389-49454-6,192.168.10.17,49454,192.168.10.3,389,6,5/7/2017 8:42,15206,17,12,3452,6660.0,1313,0,203.058823,425.778474,3069,0,555.000000,977.480342,6.650007e+05,1907.141918,543.071429,2519.931377,13391.0,0.0,15206.0,950.375000,3322.417812,13391.0,2.0,15112.0,1373.818182,4176.449588,13961.0,3.0,0,0,0,0,560,388,1117.979745,789.162173,0,3069,337.066667,704.654082,496537.374700,0,0,0,1,0,0,0,0,0,348.689655,203.058823,555.000000,560,0,0,0,0,0,0,17,3452,12,6660,29200,0,10,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,192.168.10.3-192.168.10.17-88-46126-6,192.168.10.17,46126,192.168.10.3,88,6,5/7/2017 8:42,1092,9,6,3150,3152.0,1575,0,350.000000,694.509719,1576,0,525.333333,813.842901,5.771062e+06,13736.263740,78.000000,207.000929,794.0,1.0,1092.0,136.500000,313.850738,910.0,1.0,1015.0,203.000000,333.240154,794.0,3.0,0,0,0,0,304,208,8241.758242,5494.505495,0,1576,393.875000,704.585067,496440.116700,0,0,0,1,0,0,0,0,0,420.133333,350.000000,525.333333,304,0,0,0,0,0,0,9,3150,6,3152,29200,2081,2,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN

#### drop nulls

In [ ]:
wday.dropna(inplace=True,axis=1)
wday.isna().sum()

Flow ID                        0
Source IP                      0
Source Port                    0
Destination IP                 0
Destination Port               0
Protocol                       0
Timestamp                      0
Flow Duration                  0
Total Fwd Packets              0
Total Backward Packets         0
Total Length of Fwd Packets    0
Total Length of Bwd Packets    0
Fwd Packet Length Max          0
Fwd Packet Length Min          0
Fwd Packet Length Mean         0
Fwd Packet Length Std          0
Bwd Packet Length Max          0
Bwd Packet Length Min          0
Bwd Packet Length Mean         0
Bwd Packet Length Std          0
Flow Packets/s                 0
Flow IAT Mean                  0
Flow IAT Std                   0
Flow IAT Max                   0
Flow IAT Min                   0
Fwd IAT Total                  0
Fwd IAT Mean                   0
Fwd IAT Std                    0
Fwd IAT Max                    0
Fwd IAT Min                    0
Bwd IAT Total                  0
Bwd IAT Mean                   0
Bwd IAT Std                    0
Bwd IAT Max                    0
Bwd IAT Min                    0
Fwd PSH Flags                  0
Bwd PSH Flags                  0
Fwd URG Flags                  0
Bwd URG Flags                  0
Fwd Header Length              0
Bwd Header Length              0
Fwd Packets/s                  0
Bwd Packets/s                  0
Min Packet Length              0
Max Packet Length              0
Packet Length Mean             0
Packet Length Std              0
Packet Length Variance         0
FIN Flag Count                 0
SYN Flag Count                 0
RST Flag Count                 0
PSH Flag Count                 0
ACK Flag Count                 0
URG Flag Count                 0
CWE Flag Count                 0
ECE Flag Count                 0
Down/Up Ratio                  0
Average Packet Size            0
Avg Fwd Segment Size           0
Avg Bwd Segment Size           0
Fwd Header Length.1            0
Fwd Avg Bytes/Bulk             0
Fwd Avg Packets/Bulk           0
Fwd Avg Bulk Rate              0
Bwd Avg Bytes/Bulk             0
Bwd Avg Packets/Bulk           0
Bwd Avg Bulk Rate              0
Subflow Fwd Packets            0
Subflow Fwd Bytes              0
Subflow Bwd Packets            0
Subflow Bwd Bytes              0
Init_Win_bytes_forward         0
Init_Win_bytes_backward        0
act_data_pkt_fwd               0
min_seg_size_forward           0
Active Mean                    0
Active Std                     0
Active Max                     0
Active Min                     0
Idle Mean                      0
Idle Std                       0
Idle Max                       0
Idle Min                       0
Label                          0
dtype: int64

#### remove duplicated

In [ ]:
wday.duplicated().sum()

np.int64(17)

In [ ]:
wday.drop_duplicates(inplace=True)
wday.duplicated().sum()

np.int64(0)

#### Removing Non‑Informative Metadata Columns

The following column was removed:
**`Flow ID`**

**Reason for removal:**
- The field is **identifier**, not behavioral features of the network flow.

In [ ]:

drop_cols = ['Flow ID']

wday.drop(columns=drop_cols, inplace=True)
print("Columns removed:", drop_cols)
print("New shape:", Thursday.shape)

## Saving the CSV file in our shared drive

In [ ]:
wday.to_csv('/content/drive/MyDrive/Depi Project/Cleaned Data/Cleaned_Wednesday.csv', index=False)